spring:
  application:
    name: backend  # Defines the name of the application
  profiles:
    active: dev  # Set the active profile to 'dev'
  config:
    import: classpath:safe.properties
  server:
    port: 8090  # Application will run on port 8090
  app:
    jwt:
      secret: ${JWT_SECRET}
      expirationMS: ${JWT_EXPIRATION_MS}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: ${DB_URL}  # Your DB URL
    username: ${DB_USERNAME}  # Your DB username
    password: ${DB_PASSWORD} # Your DB password
    driver-class-name: org.postgresql.Driver  # JDBC driver for PostgreSQL
    hikari:
      maximum-pool-size: 10  # Max number of connections in Hikari pool
logging:
  level.org.hibernate.SQL: DEBUG
  type.descriptor.sql: trace
  com.gkats.backend: DEBUG
